apiVersion: v1
entries:
  ascvd:
  - apiVersion: v2
    appVersion: 0.0.1
    created: "2021-07-23T09:46:25.772517-05:00"
    description: A Helm Chart to deploy the Alvearie Atherosclerotic Cardiovascular Disease (ASCVD) service.  This service will calculate the risk of cardiovascular disease based on a small set of input parameters.
    digest: b91c9094990f79c5429363195502fdcc9695ef4a775afad9623a68a8de1b121a
    home: https://github.com/Alvearie/health-analytics/tree/main/ascvd
    keywords:
    - ibm
    - alvearie
    - ascvd
    maintainers:
    - email: atclark@us.ibm.com
      name: Adam T. Clark
    name: ascvd
    type: application
    urls:
    - ascvd-0.1.0.tgz
    version: 0.1.0
  ascvd-from-fhir:
  - apiVersion: v2
    appVersion: 0.0.1
    created: "2021-07-23T09:46:25.772951-05:00"
    description: A Helm Chart to deploy the Alvearie Atherosclerotic Cardiovascular Disease (ASCVD) data extraction (from FHIR) service.
    digest: 7cc717d5681a0b351599607d52e9b6936b5736f934b8f12838cdb0e9113f21e7
    home: https://github.com/Alvearie/health-analytics/tree/main/ascvd-from-fhir
    keywords:
    - ibm
    - alvearie
    - ascvd
    maintainers:
    - email: atclark@us.ibm.com
      name: Adam T. Clark
    name: ascvd-from-fhir
    type: application
    urls:
    - ascvd-from-fhir-0.1.0.tgz
    version: 0.1.0
generated: "2021-07-23T09:46:25.771497-05:00"
