apiVersion: v1
kind: Service
metadata:
  name: ascvd-kf
  labels:
    app: ascvd-kf
spec:
  ports:
    - port: 5000
      name: ascvd-kf
      protocol: TCP
  selector:
    app: ascvd-kf
  type: NodePort
---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: ascvd-kf-ingress
  annotations:
    kubernetes.io/ingress.class: <<ingress class>>
         # IBM: public-iks-k8s-nginx
         # Azure: addon-http-application-routing
         # AWS: nginx
spec:
  rules:
    - host: <<ingress host url>>
      http:
        paths:
          - path: /
            backend:
              serviceName: ascvd-kf
              servicePort: 5000
---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: ascvd-kf
spec:
  selector:
    matchLabels:
      app: ascvd-kf
  template:
    metadata:
      labels:
        app: ascvd-kf
    spec:
      containers:
        - name: ascvd-kf
          image: <<GROUP>>/ascvd-kf:<<TAG>>
          imagePullPolicy: Always
          env:
            - name: FHIRENDPOINT
              value: "<<fhirserver base url>>/fhir-server/api/v4>>"
            - name: FHIRUSERNAME
              value: "<<username>>"
            - name: FHIRPW
              value: "<<password>>"
            - name: KFENDPOINT
              value: "<<public kubeflow endpoint root url>>"
            - name: KUBEFLOWPROFILENAME
              value: "<<kubeflow user profile name>>"
            - name: ASCVDENDPOINT
              value: "<<ascvd service endpoint>>/fhir"
