apiVersion: v1
kind: Service
metadata:
  name: ascvd-from-fhir
  labels:
    app: ascvd-from-fhir
spec:
  ports:
    - port: 5000
      name: ascvd-from-fhir
      protocol: TCP
  selector:
    app: ascvd-from-fhir
  type: NodePort
---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: ascvd-from-fhir-ingress
  annotations:
    kubernetes.io/ingress.class: public-iks-k8s-nginx
spec:
  rules:
    - host:
      http:
        paths:
          - path: /
            backend:
              serviceName: ascvd-from-fhir
              servicePort: 5000
---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: ascvd-from-fhir
spec:
  selector:
    matchLabels:
      app: ascvd-from-fhir
  template:
    metadata:
      labels:
        app: ascvd-from-fhir
    spec:
      containers:
        - name: ascvd-from-fhir
          image: quay.io/alvearie/ascvd_from_fhir:0.0.3
          imagePullPolicy: Always
          env:
            - name: ASCVD_URL
              value: http://ascvd:8080
