apiVersion: v1
kind: Service
metadata:
  name: ascvd-from-fhir
  labels:
    app: ascvd-from-fhir
spec:
  ports:
    - port: 5000
      name: ascvd-from-fhir
      protocol: TCP
  selector:
    app: ascvd-from-fhir
  type: NodePort
---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: ascvd-from-fhir-ingress
  annotations:
    kubernetes.io/ingress.class: <<INGRESS_CLASS>>
         # IBM: public-iks-k8s-nginx
         # Azure: addon-http-application-routing
         # AWS: nginx
spec:
  rules:
    - host: atc-ascvd-ascvd-from-fhir.<<INGRESS_SUBDOMAIN>>
      http:
        paths:
          - path: /
            backend:
              serviceName: ascvd-from-fhir
              servicePort: 5000
---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: ascvd-from-fhir
spec:
  selector:
    matchLabels:
      app: ascvd-from-fhir
  template:
    metadata:
      labels:
        app: ascvd-from-fhir
    spec:
      containers:
        - name: ascvd-from-fhir
          image: docker.io/<<GROUP>>/ascvd_from_fhir:0.0.1
          imagePullPolicy: Always
          env:
            - name: ASCVD_URL
              value: <<ASCVD_SERVICE_URL>>