apiVersion: v1
kind: Service
metadata:
  name: {{ include "ascvd-from-fhir.fullname" . }}
  labels:
    {{- include "ascvd-from-fhir.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: {{ include "ascvd-from-fhir.fullname" . }}
  selector:
    {{- include "ascvd-from-fhir.selectorLabels" . | nindent 4 }}